'use client'

import { Button } from '@/components/ui/button'
import Link from 'next/link'

export default function TermsPage() {
  return (
    <main className="flex flex-col">
      {/* Hero Section */}
      <section className="relative py-20 md:py-32 overflow-hidden">
        {/* Background gradient */}
        <div className="absolute inset-0 bg-gradient-to-b from-background to-background/80 -z-10"></div>
        
        {/* Background pattern */}
        <div className="absolute inset-0 -z-20">
          <div className="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:24px_24px]"></div>
        </div>
        
        {/* Accent elements */}
        <div className="absolute top-0 right-0 -z-10 transform translate-x-1/2 -translate-y-1/4">
          <div className="w-[300px] h-[300px] rounded-full bg-primary/20 blur-[100px]"></div>
        </div>
        
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-8 md:space-y-12">
            <div className="inline-flex items-center rounded-full border px-2.5 py-0.5 text-sm font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-primary/10 text-primary">
              <span>Legal</span>
              <span className="ml-1 text-primary">📝</span>
            </div>
            
            <h1 className="text-4xl md:text-6xl font-bold tracking-tighter max-w-3xl">
              Terms of Service
            </h1>
            
            <p className="text-xl text-muted-foreground max-w-2xl">
              Last updated: October 15, 2023
            </p>
          </div>
        </div>
      </section>
      
      {/* Terms of Service Content */}
      <section className="py-20">
        <div className="container px-4 md:px-6">
          <div className="max-w-3xl mx-auto prose prose-slate">
            <h2>Introduction</h2>
            <p>
              Welcome to IdeaStruct. These Terms of Service ("Terms") govern your use of our website and services. By accessing or using our service, you agree to be bound by these Terms. If you disagree with any part of the Terms, you may not access the service.
            </p>
            
            <h2>Definitions</h2>
            <ul>
              <li><strong>"Service"</strong> refers to the IdeaStruct website and all services provided by IdeaStruct.</li>
              <li><strong>"User"</strong> refers to any individual who accesses or uses the Service.</li>
              <li><strong>"Content"</strong> refers to all information, data, text, software, graphics, and other materials that may be accessed through the Service.</li>
              <li><strong>"Blueprint"</strong> refers to the output generated by our Service based on user inputs.</li>
            </ul>
            
            <h2>Account Registration</h2>
            <p>
              To use certain features of the Service, you may be required to register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
            </p>
            <p>
              You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password. You agree not to disclose your password to any third party.
            </p>
            
            <h2>User Content</h2>
            <p>
              Our Service allows you to input information about your app ideas to generate blueprints. You retain all rights to your ideas and the content you provide.
            </p>
            <p>
              By submitting content to our Service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, process, and display your content solely for the purpose of providing the Service to you.
            </p>
            <p>
              You represent and warrant that:
            </p>
            <ul>
              <li>You own or have the necessary rights to the content you submit</li>
              <li>The content does not violate the rights of any third party</li>
              <li>The content complies with these Terms and applicable law</li>
            </ul>
            
            <h2>Intellectual Property</h2>
            <p>
              The Service and its original content, features, and functionality are and will remain the exclusive property of IdeaStruct and its licensors. The Service is protected by copyright, trademark, and other laws.
            </p>
            <p>
              Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of IdeaStruct.
            </p>
            
            <h2>Blueprints and Generated Content</h2>
            <p>
              The blueprints generated by our Service are provided for informational purposes only. While we strive to provide accurate and useful information, we make no representations or warranties about the accuracy, completeness, or suitability of the blueprints for any purpose.
            </p>
            <p>
              You own the blueprints generated based on your inputs. However, we may use anonymized data from blueprints to improve our Service.
            </p>
            
            <h2>Subscription and Billing</h2>
            <p>
              Some features of the Service require a subscription. By subscribing to our Service, you agree to pay the fees as described at the time of purchase.
            </p>
            <p>
              Subscriptions automatically renew unless canceled at least 24 hours before the end of the current period. You can cancel your subscription at any time through your account settings.
            </p>
            <p>
              Refunds are provided in accordance with our Refund Policy.
            </p>
            
            <h2>Limitation of Liability</h2>
            <p>
              In no event shall IdeaStruct, its directors, employees, partners, agents, suppliers, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
            </p>
            <ul>
              <li>Your access to or use of or inability to access or use the Service</li>
              <li>Any conduct or content of any third party on the Service</li>
              <li>Any content obtained from the Service</li>
              <li>Unauthorized access, use, or alteration of your transmissions or content</li>
            </ul>
            
            <h2>Disclaimer</h2>
            <p>
              Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied.
            </p>
            
            <h2>Governing Law</h2>
            <p>
              These Terms shall be governed by the laws of the State of California, without respect to its conflict of laws principles.
            </p>
            
            <h2>Changes to Terms</h2>
            <p>
              We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect.
            </p>
            <p>
              By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms.
            </p>
            
            <h2>Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p>
              Email: legal@ideastruct.com<br />
              Address: 123 Innovation Street, San Francisco, CA 94103, USA
            </p>
          </div>
          
          <div className="max-w-3xl mx-auto mt-12 text-center">
            <p className="text-muted-foreground mb-6">
              If you have any questions about our Terms of Service, please contact us.
            </p>
            <Button asChild>
              <Link href="/contact">
                Contact Us
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </main>
  )
}
